info:
  contact: {}
paths:
  /api/v1/notes:
    get:
      consumes:
        - application/json
      description: Fetch all data
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get all data
      tags:
        - energydata
  /api/v1/notes:id:
    get:
      consumes:
        - application/json
      description: Fetch data by id
      parameters:
        - description: entryId
          in: path
          name: id
          required: true
          type: integer
      produces:
        - application/json
      responses:
        '200':
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get data by id
      tags:
        - energydata
swagger: '2.0'
